import Head from "next/head";
import Image from "next/image";
import Feature from "../Components/Feature";
import Title from "../Components/Title";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-[url(../public/assets/home.jpeg)] bg-cover bg-no-repeat bg-bottom flex items-center justify-center">
        <div className="flex flex-col justify-center items-center text-white w-4/5">
          <h1 className="text-5xl pb-2 text-center">
            Find the Perfect Shortlet Today
          </h1>
          <span className="text-center mx-auto">
            We offer a wide range of comfortable and beautiful apartments at
            affordible Prices
          </span>
          <div className="flex w-full justify-center mt-10">
            <div className="bg-white flex w-3/5 mr-4">
              <input type="text" placeholder="" />
            </div>
            <button className="bg-black px-6 py-2 text-white">Search</button>
          </div>
        </div>
      </main>
      <div className="container mx-auto">
        <section className="py-10">
          <Title text={"Our Apartments"} />
          <div className="grid md:grid-cols-2 grid-rows-2 gap-6 px-4 text-white">
            <div className="bg-[url(../public/assets/room3.jpeg)] row-span-2 min-h-[20rem] relative bg-cover bg-bottom before:absolute before:w-full before:h-full before:bg-black before:opacity-40 flex items-end">
              <div className="flex justify-between px-8 py-8 text-2xl text-bold">
                <span className="z-10">Rooms (3)</span>
                <img src="" alt="" />
              </div>
            </div>
            <div className="bg-[url(../public/assets/penthouse1.jpeg)]  min-h-[20rem] bg-cover bg-bottom relative before:absolute before:w-full before:h-full before:bg-black before:opacity-40 flex items-end">
              <div className="flex justify-between px-8 py-8 text-2xl text-bold">
                <span className="z-10">Penthouse (1)</span>
                <img src="" alt="" />
              </div>
            </div>
            <div className="bg-[url(../public/assets/home.jpeg)]  min-h-[20rem] bg-cover bg-bottom relative before:absolute before:w-full before:h-full before:bg-black before:opacity-40 flex items-end">
              <div className="flex justify-between px-8 py-8 text-2xl text-bold">
                <span className="z-10">Suite (1)</span>
                <img src="" alt="" />
              </div>
            </div>
          </div>
        </section>
        <section className="px-10 py-10">
          <Title text={"Why Choose Us"} />
          <div className="grid sm:grid-cols-2 gap-4">
            <Feature
              header={"Affordable Prices"}
              src="blue-icon.png"
              text={"Our prices are 100% affordable & budget friendly"}
            />
            <Feature
              header={"Uninterrupted power supply"}
              src="yellow-icon.png"
              text={
                "We provided 24/7 power supply at all our apartments. This ensures all electrical appliances such as Air-conditioner, TV, Fridge, etc, are functioning well."
              }
            />
            <Feature
              header={"Secured & Comfortable"}
              src="green-icon.png"
              text={
                "At Aphlaapartments our customer is our pride, and we ensure that they have a delightful stay with on demand customer services to cateer to their needs."
              }
            />
            <Feature
              header={"Excellent Customer Service"}
              src="black.png"
              text={
                "At Aphlaapartments our customer is our pride, and we ensure that they have a delightful stay with on demand customer services to cateer to their needs."
              }
            />
          </div>
          <div className="flex items-center w-full justify-center py-6">
          <button className="bg-black px-6 py-2 text-white">
            Book Now
          </button>
          </div>
        </section>
      </div>
    </div>
  );
}
